title: My personal website
description: A collection of my Markdown articles

remote_theme: just-the-docs/just-the-docs
color_scheme: light
search_enabled: true

baseurl: ""  
url: "https://ridhoma.github.io"
